name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean test integrationTest build nativeCompile
      - name: Test native image
        run: |
          # run several iterations to test various pathways when generating data
          for i in {0..10}; do
            ./cli-bot/build/native/nativeCompile/faker-bot  list --verbose >/dev/null || false
            ./cli-bot/build/native/nativeCompile/faker-bot  lookup a --verbose >/dev/null || false
          done


